### ISSUE TITLE
Export boolean values as true/false

### ISSUE THREAD

**Issue by ValeSauer** [sphereio/sphere-product-type-export#18]
Boolean values such as isRequired or isSearchable should be exported as true or false as https://github.com/sphereio/sphere-product-type-json-generator expects either true or false. Currently it is exported either as 1 or "".
1 => true
  => false

**Comment by hisabimbola** [comment]
the [csv](https://github.com/wdavidw/node-csv-stringify/blob/master/src/index.coffee.md) being used does this by default, we can turn it off.

**Comment by hisabimbola** [comment]
look at this issue, the reason it was done was because 'true' or 'false' is a javascript thing, so if a csv wants to be parse via another language like python, it's not going to work.

Since most likely the csv will be used by `sphere-product-type-json-generator` I think we can turn this behaviour off

**Comment by junajan** [comment]
There is that `@options.formatters.bool` option so I will modify it so it prints out `true` or `false` instead of `1` or an empty string

**Comment by junajan** [comment]
Also, we should check that it will work on both - xlsx and csv filetypes

**Comment by junajan** [comment]
I tried to export some productTypes to CSV/XLSX and import them using `sphere-product-type-json-generator` and it looks like the boolean information is not transferred properly:

**Exported attributes with isSearchable = true:**
<img width="892" alt="screen shot 2017-07-13 at 13 44 02" src="https://user-images.githubusercontent.com/1090382/28164845-8f267666-67d1-11e7-8e1b-2cedc87d78a9.png">

**Imported productTypes:**
<img width="500" alt="screen shot 2017-07-13 at 13 46 16" src="https://user-images.githubusercontent.com/1090382/28164886-b5cc24a0-67d1-11e7-8ff3-70a65fa02847.png">
