### ISSUE TITLE
Support CSV items containing comma

### ISSUE THREAD

**Issue by junajan** [sphereio/sphere-product-type-export#9]
### Description
When exporting productTypes, CSV data are currently not escaped from comma character: https://github.com/sphereio/sphere-product-type-export/blob/master/src/product-type-export.js#L410
So if you export this LENUM item:
```js
{
   "key": "sg",
   "label": {
   "de": "SG (Frische-EAN, var. Preis, SAN + Gebindez.)"
  }
},
```
Comma in labe.de won't be escaped and thus it will be readed incorrencly when importing data back to sphere.

### Expected Behavior
It should escape values containing a comma using quotes.

**Comment by hisabimbola** [comment]
I think this bug is applicable to any delimiter used and not only _comma_

**Comment by hisabimbola** [comment]
@junajan please update the label if you working on this issue, and also can you share how you intend to fix this?

**Comment by junajan** [comment]
@hisabimbola - with this PR https://github.com/sphereio/sphere-product-type-export/pull/7 we started using `csv` module which should automatically escape special characters so I will close this issue because it is not a problem anymore.
